# Generated by Django 5.2.5 on 2025-09-09 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='id_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='authentication.departments'),
        ),
        migrations.AddField(
            model_name='departments',
            name='id_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='authentication.countries'),
        ),
        migrations.AddField(
            model_name='users',
            name='id_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='authentication.cities'),
        ),
    ]
