# Generated by Django 5.2.5 on 2025-10-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_cities_id_department_departments_id_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
